### ISSUE TITLE
actual disk_lev for VM's

### ISSUE THREAD

**Issue by Lueghi** [iobroker-community-adapters/ioBroker.proxmox#245] opened 2022-10-31 17:22 UTC
The disk_lev for VM's is always 0. As far as I know, this is a restriction of proxmox.
But inside the VM you can explore the disk_lev with the following command:
`df -h | grep `hostname` | awk '{print $5}'`

And you can set the disk_lev in proxmox with the following command with simple-api (example 78%):
`http://iobroker_ip:8087/set/proxmox.0.qemu_HOSTNAME.disk_lev?value=78&prettyPrint`

Unfortunatly the adapter reset the disk_lev always back to 0.

Is it possible to suppress the reset of disk_lev? I think this would be helpfull for the administration of proxmox with VM's.

**Comment by arteck** [comment] 2023-09-18 04:51
> the reset of disk_lev? I think this would be helpfull for the administration of proxmox with VM's.

really.. administration from iobroker..

**Comment by klein0r** [comment] 2023-09-18 06:40
> Is it possible to suppress the reset of disk_lev? I think this would be helpfull for the administration of proxmox with VM's.

But: why? It's not planned to replace the Proxmox Web UI with this adapter.

> The disk_lev for VM's is always 0.

Duplicate of #55 (?)

**Comment by arteck** [comment] 2023-10-07 06:53
we can close here

**Closed by arteck** 2023-10-07 06:53 UTC
Labels: enhancement

**Comment by Lueghi** [comment] 2024-01-07 15:30
I don't want to replace the proxmox UI, I only want to visualize the data. And the data of the adapter is not right or can't be determined by the adapter. That's the reason I was asking if the adapter shall not set this value for VM's.
And yes, it is a duplicate of #55. Sorry for this.
